#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/WebFrontend/WebFrontend.csproj", "src/WebFrontend/"]
COPY ["src/DB/DB.csproj", "src/DB/"]
COPY ["src/Model/Model.csproj", "src/Model/"]
RUN dotnet restore "WebFrontend/WebFrontend.csproj"
COPY . .
WORKDIR "/src/WebFrontend"
RUN dotnet build "WebFrontend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebFrontend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebFrontend.dll"]